<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Servexa.Application\Servexa.Application.csproj" />
    <ProjectReference Include="..\Servexa.Domain\Servexa.Domain.csproj" />
    <ProjectReference Include="..\Servexa.Shared\Servexa.Shared.csproj" />
  </ItemGroup>

</Project>
